### ISSUE TITLE
代理验证有问题

### ISSUE THREAD

**Issue by jax777** [qiyeboy/IPProxys#1]
很多代理其实只是个网站，并没有代理功能
验证代理还要判断返回内容是不是访问的网站
如访问 http://utp.qq.com/  返回值里就应该有代理ip  www.qq.com  等关键字

**Comment by qiyeboy** [comment]
谢谢反馈，我也发现了这个问题，今天就修复一下

**Comment by qiyeboy** [comment]
谢谢反馈，我也发现了这个问题，今天就修复一下

**Comment by sweetpineapple** [comment]
我在linux一开始好好的，运行一段时间之后，出现这个错误：
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by qiyeboy** [comment]
已经修复
