### ISSUE TITLE
这是怎么个情况，自动退出了吗

### ISSUE THREAD

**Issue by debbbbie** [qiyeboy/IPProxys#4]
![image](https://cloud.githubusercontent.com/assets/233115/20503260/c2787c10-b07c-11e6-9f7a-dde20d1acb71.png)

**Comment by debbbbie** [comment]
![image](https://cloud.githubusercontent.com/assets/233115/20503280/dccabe02-b07c-11e6-9dad-9594e4442122.png)

**Comment by qiyeboy** [comment]
你使用的系统版本和Python版本是什么

**Comment by debbbbie** [comment]
mac os x
python 2.7
你的 test 下的几个文件都是能正常运行的

**Comment by debbbbie** [comment]
@qiyeboy

**Comment by qiyeboy** [comment]
mac os x下没测试过，只是测试了ubuntu和windows, 我装个mac os x试试@debbbbie

**Comment by debbbbie** [comment]
要装黑苹果吗，据说很麻烦，要不然你看看怎么把 log 打出来，我帮你调试？  @qiyeboy

**Comment by qiyeboy** [comment]
我在kali上运行也出现了这样的问题，应该是同样的问题，没有抛出异常，直接退出。。。。，我得好好改改 @debbbbie

**Comment by debbbbie** [comment]
👍

**Comment by qiyeboy** [comment]
pip freeze > out.txt ,把out.txt发我邮箱 @debbbbie

**Comment by debbbbie** [comment]
OK

**Comment by debbbbie** [comment]
altgraph==0.12
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.4.0
butterfly==1.5.10
certifi==2015.4.28
cffi==1.1.2
cryptography==0.9.1
enum34==1.0.4
gevent==1.0.2
gfwlist2pac==1.1.3
greenlet==0.4.9
html5lib==0.9999999
idna==2.0
ipaddress==1.0.7
lxml==3.6.4
macholib==1.7
mercurial==3.9.1
modulegraph==0.12.1
powerline-status==2.3
py2app==0.9
pyasn1==0.1.8
pycparser==2.14
pygobject==3.20.1
pyobjc-core==3.0.4
pyOpenSSL==0.15.1
redis==2.10.3
requests==2.7.0
rumps==0.2.1
six==1.10.0
tornado==4.2
tornado-systemd==1.0.1
vboxapi==1.0
virtualenv==15.0.1

**Comment by qiyeboy** [comment]
找到问题了，gevent版本过低。使用 pip install gevent --upgrade更新一下版本 @debbbbie

**Comment by debbbbie** [comment]
@qiyeboy It Works
