### ISSUE TITLE
能不能配置选用不同的数据库, 比如支持redis?

### ISSUE THREAD

**Issue by Petelin** [qiyeboy/IPProxys#7]
sqlite 模块确实是python内置的,但是有些机器上是没有sqlite3模块的(比如我的机器上),redis 是一个更好的选择呀~~,我现在只能改成连接mysql,如果能抽象出来一套操作的话,就可以改成redis了.

**Comment by qiyeboy** [comment]
当初选择sqlite是因为大多数linux系统都内置了,而且移动也方便，之后会留出接口适配不同的数据库，TODO里面就是接下来要做的事情 @Petelin
